module Message
 

  def welcome
    puts "Welcome to Mastermind!"
  end
  
  def player_choice 
    puts "Would you like to (p)lay, read the (i)nstructions, or (q)uit? >"
  end
  
  def game_start
    puts "I have generated a beginner sequence with four elements made up of: (r)ed,
    (g)reen, (b)lue, and (y)ellow. Use (q)uit at any time to end the game.
    What's your guess?"
  end

  def instructions
     puts "Mastermind is a game where you must try to guess the secret combination.
          The combination will be randomly generated by the computer. Your goal
          will be to guess this secret combination in as few guesses as possible.
          You will be using 4 different colored pegs. The randomly generated combination
          will also be made up of the same pegs:(R)ed, (G)reen, (B)lue and (Y)ellow.
          For example the computer might generate a secret code of 'RRRR' which you will
          not be able to see. You start by guessing a 4 peg combination such as 'RRBG'.
          The program will compare your guess with the randomly generated combo and let
          you know how close your guess was. You may use the clues provided to continue
          guessing until you have guessed the correct combination."
  end

  def too_long
    puts "That guess was way too long. Must be 4 characters only! Guess again!"
  end

  def too_short
    puts "That guess was way too short. Must be 4 characters only! Guess again!"
  end

  def invalid_entry
    puts "Sorry invalid entry try again!"
  end
  

  def player_wins
    puts "Congratulations! You guessed #{} in #{} guesses over #{}"

    puts "Do you want to (p)lay again or (q)uit?" 
  end
  
end



